# Request from browser => nginx => static or php, if not static => php-apache => static or php
# http://localhost:8000/nginx-index.html
# http://localhost:8000/apache-index.html
# http://localhost:8000/index.php
version: '3'
services:
  mysql-mariadb:
    build: './mysql'
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: ./.env
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
  nginx:
    build: './nginx'
    volumes:
      - ./nginx-public_html:/home/public_html

    ports:
      - 80:80
    depends_on:
      - php-apache
    restart: always
  php-apache:
    build: './php-apache'
    ports:
      - 8001:8001
    volumes:
      - ./public_html:/home/public_html
      - ./logs:/var/log/apache2

    env_file: ./.env
    restart: always
    depends_on:
      - mysql-mariadb
