version: '3'
services:
  mysql-mariadb:
    build: './mysql'
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file: ./.env
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
  nginx:
    build: './nginx'
    volumes:
      - ./nginx-public_html:/home/public_html
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - php-apache
    restart: always
  php-apache:
    build: './php-apache'
    ports:
      - 8001:8001
    expose: 
      - 8001
    volumes:
      - ./public_html:/home/public_html:rw
      - ./logs:/var/log/apache2

    env_file: ./.env
    restart: always
    depends_on:
      - mysql-mariadb
  #postgres:
  #  image: postgres:12-alpine
  #  restart: always
  #  ports:
  #    - 5432:5432
  #  expose:
  #    - 5432
  #  volumes:
  #    - ./data-postgres/:/var/lib/postgresql/data
  #  environment:
  #    - POSTGRES_PASSWORD=12345678
  #    - POSTGRES_USER=binguito_user
  #    - POSTGRES_DB=binguito_db
  #lazydocker:
#    #: lazyteam/lazydocker
  #  container_name: lazydocker
  #  stdin_open: true
  #  tty: true
  #  volumes:
   #   - /var/run/docker.sock:/var/run/docker.sock
   #   - ./config:/.config/jesseduffield/lazydocker